#!/bin/bash
#SBATCH --qos=debug
#SBATCH --nodes=2
#SBATCH --tasks-per-node=32
#SBATCH --time=10:00
#SBATCH --licenses=cscratch1
#SBATCH --constraint=haswell

# copy metadata server to current dir
rm unimos_server.conf Gorila_cred_conf gray_scott_pe_* conf* core cred inline_*.log

# key varaibles
SIMTASK=36

srun -C haswell -n $SIMTASK -c 1 --cpu_bind=cores ./example/gray-scott-inline ~/cworkspace/src/Gorilla/example/gssimulation/settings.json gni &> inline_sim.log

sleep 5